/**
 * Turns the in-app "what's new" body into groups the settings page can render.
 *
 * The body is generated by `.github/scripts/build-update-notes.mjs` and carried
 * on the updater manifest: `### 分组` headings over `- 条目` bullets. Rendered
 * raw it would show the `###` and the `-`, and a markdown renderer is far more
 * machinery than two line shapes need, so the shapes are split here.
 *
 * Deliberately tolerant: a line that is neither a heading nor a bullet is kept
 * as an item, so a hand-written note reaches the user instead of being dropped.
 */
export type UpdateNoteGroup = { title: string; items: string[] }

export function parseUpdateNotes(notes: string | undefined): UpdateNoteGroup[] {
  if (!notes) return []

  const groups: UpdateNoteGroup[] = []

  for (const line of notes.split("\n")) {
    const text = line.trim()
    if (!text) continue

    if (text.startsWith("#")) {
      groups.push({ title: text.replace(/^#+\s*/, ""), items: [] })
      continue
    }

    const item = text.replace(/^[-*]\s*/, "")
    const current = groups[groups.length - 1]
    if (current) current.items.push(item)
    else groups.push({ title: "", items: [item] })
  }

  return groups
}
